const NATION = {
  name: "Republic of Varde",
  formerly: "Saaremaa",
  founded: 2026,
  population: 31000,
  area: 2673,
  capital: "Kuressaare",
  currency: "Varde Kroon (VRK) — pegged 1:1 to EUR",
  flag: "🏝️",
};

const POLICIES = [
  { id:"tax",        year:1, icon:"💰", title:"0% income tax under €2,500/month — 15% above",                    source:"🇦🇪 UAE + 🇧🇭 Bahrain",       fact:"UAE has 0% income tax. Bahrain kept it simple. Both attract global talent." },
  { id:"corporate",  year:1, icon:"🏢", title:"0% corporate tax on reinvested profits — 15% on dividends only",   source:"🇮🇪 Ireland adapted",          fact:"Ireland's 12.5% rate attracted Google, Apple, Meta. Varde goes further — reinvest and pay nothing." },
  { id:"ubi",        year:1, icon:"💸", title:"Universal Basic Income — €800/month for every citizen",            source:"🇫🇮 Finland + 🇳🇴 Norway",    fact:"Finland's UBI pilot showed better mental health, more entrepreneurship, and same employment rates." },
  { id:"healthcare", year:2, icon:"🏥", title:"Universal healthcare — single payer, fully public",                source:"🇹🇼 Taiwan",                   fact:"Taiwan's single-payer covers 99.9% of citizens at 6.6% of GDP — half what the US spends for worse outcomes." },
  { id:"education",  year:2, icon:"🎓", title:"Free education — kindergarten through university",                  source:"🇩🇪 Germany + 🇩🇰 Denmark",   fact:"Germany abolished university fees in 2014. Graduate debt dropped to zero. International applications tripled." },
  { id:"housing",    year:2, icon:"🏠", title:"Public housing — 70% state-built, sold at cost price",             source:"🇸🇬 Singapore",                fact:"Singapore's HDB scheme means 89% of citizens OWN their home. Homelessness is functionally zero." },
  { id:"banking",    year:3, icon:"🏦", title:"Public non-profit bank — no fees, no minimum balance",             source:"🇩🇪 Sparkasse model",          fact:"Germany's Sparkasse banks return profits to communities. Zero fees. 100% financial inclusion." },
  { id:"privacy",    year:3, icon:"🔐", title:"Constitutional right to privacy — strongest in the world",         source:"🇨🇭 Switzerland + 🇩🇪 Germany",fact:"Switzerland and Germany set the gold standard. Varde goes further — you legally OWN your data." },
  { id:"egov",       year:3, icon:"💻", title:"Full e-government — company in 18 mins, taxes auto-filed",         source:"🇪🇪 Estonia",                  fact:"Estonia's e-government saves citizens 5 working days per year. 99% of services are online." },
  { id:"workweek",   year:4, icon:"📅", title:"4-day work week — 32 hours, same pay",                             source:"🇮🇸 Iceland",                  fact:"Iceland's trials showed same or better productivity. 86% of workforce now on reduced hours." },
  { id:"immigration",year:4, icon:"🌍", title:"Open skilled immigration — citizenship in 5 years",                source:"🇨🇦 Canada points system",     fact:"Canada's points-based immigration fuels 400k+ skilled arrivals yearly. GDP per capita grows 1.5% faster than USA." },
  { id:"energy",     year:4, icon:"🌿", title:"100% renewable energy — wind + solar + tidal",                     source:"🇮🇸 Iceland + 🇩🇰 Denmark",   fact:"Denmark hit 53% wind energy in 2022. Iceland runs on 100% renewable. Varde has Baltic wind + tidal potential." },
  { id:"drugs",      year:5, icon:"⚕️", title:"Full drug decriminalization + regulated cannabis",                  source:"🇵🇹 Portugal",                 fact:"Portugal decriminalized all drugs in 2001. Drug deaths fell 80%. HIV infections fell 95%. Prison costs halved." },
  { id:"wealth",     year:5, icon:"📈", title:"Sovereign wealth fund — 30% of all tax revenue invested",          source:"🇳🇴 Norway",                   fact:"Norway's $1.4 trillion fund means every citizen owns $250,000 in assets." },
  { id:"wages",      year:6, icon:"⚖️", title:"Max wage ratio — CEO earns max 20x lowest paid employee",          source:"🇨🇭 Switzerland referendum",   fact:"Countries with lower wage ratios have higher happiness and lower crime rates." },
  { id:"parental",   year:6, icon:"👶", title:"18 months paid parental leave — split between parents",             source:"🇸🇪 Sweden",                   fact:"Sweden's system leads to highest female workforce participation globally." },
  { id:"mental",     year:7, icon:"🧠", title:"Free mental health care — therapy for all, no waitlist",           source:"🇮🇸 Iceland",                  fact:"Iceland has lowest depression rates in Europe. Every €1 invested returns €4." },
  { id:"eresidency", year:7, icon:"🌐", title:"e-Residency 2.0 — run a Varde company from anywhere on Earth",    source:"🇪🇪 Estonia improved",         fact:"Estonia's e-residency added €1.8B to its economy from non-resident companies." },
  { id:"voting",     year:8, icon:"🗳️", title:"Ranked choice voting + citizens assembly",                         source:"🇮🇪 Ireland",                  fact:"Ireland's citizens assemblies solved issues politicians couldn't touch. RCV eliminates tactical voting." },
  { id:"startup",    year:8, icon:"🚀", title:"Public startup fund — 0% interest loans, equity model",            source:"🇮🇱 Israel",                   fact:"Israel's Yozma program created the world's highest startup density per capita." },
];

const EVENTS = [
  { year:2,  icon:"💻", text:"First international tech company registers via e-Residency. 340 jobs created.",                       stat:"gdp",   delta:3  },
  { year:3,  icon:"🏥", text:"Finland sends healthcare advisors. First public hospital opens in Kuressaare.",                       stat:"happy", delta:5  },
  { year:4,  icon:"🏠", text:"Housing waitlist clears — 2,100 families moved into affordable homes.",                               stat:"happy", delta:7  },
  { year:4,  icon:"💰", text:"First sovereign wealth fund dividend paid — €240 per citizen.",                                       stat:"happy", delta:4  },
  { year:5,  icon:"🌍", text:"Population hits 38,000. Skilled immigrants arriving at 800 per year.",                               stat:"pop",   delta:8  },
  { year:5,  icon:"⚕️", text:"Drug decriminalization passes. Police redirect to violent crime. Crime down 31%.",                    stat:"happy", delta:6  },
  { year:6,  icon:"🚀", text:"Varde ranked #1 in Europe for startup density per capita.",                                          stat:"gdp",   delta:8  },
  { year:7,  icon:"🌿", text:"100% renewable energy achieved. Selling surplus to Latvia via undersea cable.",                      stat:"gdp",   delta:5  },
  { year:7,  icon:"🏆", text:"UN Human Development Report: Varde enters top 10 globally.",                                        stat:"happy", delta:8  },
  { year:8,  icon:"🏘️", text:"Zero homelessness declared. Last shelter converted to co-working space.",                            stat:"happy", delta:10 },
  { year:9,  icon:"🌐", text:"e-Residency reaches 50,000 non-resident companies. Tax revenue +€180M.",                            stat:"gdp",   delta:12 },
  { year:10, icon:"📈", text:"GDP per capita crosses €40,000 — surpassing Estonia, Latvia and Lithuania.",                        stat:"gdp",   delta:10 },
  { year:11, icon:"🧠", text:"Mental health crisis rate falls to lowest in Europe. Iceland model validated.",                      stat:"happy", delta:6  },
  { year:12, icon:"📅", text:"4-day work week study: Varde workers 22% more productive than EU average.",                         stat:"gdp",   delta:5  },
  { year:13, icon:"💸", text:"Sovereign wealth fund hits €2.1B. Annual citizen dividend raised to €800.",                         stat:"happy", delta:8  },
  { year:14, icon:"🦄", text:"First Varde-born unicorn — logistics AI company valued at €1.4B.",                                  stat:"gdp",   delta:10 },
  { year:15, icon:"👶", text:"Population 61,000. Birth rate highest in Europe — families can afford children.",                   stat:"pop",   delta:12 },
  { year:16, icon:"😊", text:"World Happiness Report: Varde ranks #2 globally, behind only Finland.",                             stat:"happy", delta:10 },
  { year:18, icon:"⚡", text:"Baltic Sea clean energy corridor launches — Varde as hub. €400M in contracts.",                     stat:"gdp",   delta:14 },
  { year:20, icon:"🏆", text:"GDP per capita €67,000 — top 5 in the world. Population 85,000.",                                  stat:"gdp",   delta:8  },
];

const WORLD_COMPARISON = [
  { name:"Luxembourg",  gdp:128820, happy:73 },
  { name:"Switzerland", gdp:98767,  happy:78 },
  { name:"Norway",      gdp:89154,  happy:79 },
  { name:"USA",         gdp:76329,  happy:68 },
  { name:"Denmark",     gdp:67984,  happy:82 },
  { name:"Sweden",      gdp:61867,  happy:80 },
  { name:"Finland",     gdp:53654,  happy:83 },
  { name:"Germany",     gdp:48717,  happy:72 },
  { name:"Estonia",     gdp:28765,  happy:62 },
  { name:"Latvia",      gdp:22531,  happy:58 },
];
